# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_NumPad.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NumPad(object):
    def setupUi(self, NumPad):
        NumPad.setObjectName("NumPad")
        NumPad.setWindowModality(QtCore.Qt.ApplicationModal)
        NumPad.resize(368, 290)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NumPad.sizePolicy().hasHeightForWidth())
        NumPad.setSizePolicy(sizePolicy)
        NumPad.setMaximumSize(QtCore.QSize(400, 290))
        self.gridLayout_2 = QtWidgets.QGridLayout(NumPad)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Range_label = QtWidgets.QLabel(NumPad)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Range_label.setFont(font)
        self.Range_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Range_label.setObjectName("Range_label")
        self.gridLayout_2.addWidget(self.Range_label, 0, 0, 1, 1)
        self.newVal_label = QtWidgets.QLabel(NumPad)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.newVal_label.setFont(font)
        self.newVal_label.setFrameShape(QtWidgets.QFrame.Box)
        self.newVal_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.newVal_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.newVal_label.setObjectName("newVal_label")
        self.gridLayout_2.addWidget(self.newVal_label, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton1 = QtWidgets.QPushButton(NumPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton1.sizePolicy().hasHeightForWidth())
        self.pushButton1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton1.setFont(font)
        self.pushButton1.setObjectName("pushButton1")
        self.gridLayout.addWidget(self.pushButton1, 2, 0, 1, 1)
        self.pushButton0 = QtWidgets.QPushButton(NumPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton0.sizePolicy().hasHeightForWidth())
        self.pushButton0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton0.setFont(font)
        self.pushButton0.setObjectName("pushButton0")
        self.gridLayout.addWidget(self.pushButton0, 3, 0, 1, 1)
        self.pushButtonSign = QtWidgets.QPushButton(NumPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSign.sizePolicy().hasHeightForWidth())
        self.pushButtonSign.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButtonSign.setFont(font)
        self.pushButtonSign.setObjectName("pushButtonSign")
        self.gridLayout.addWidget(self.pushButtonSign, 3, 1, 1, 1)
        self.pushButtonPnt = QtWidgets.QPushButton(NumPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPnt.sizePolicy().hasHeightForWidth())
        self.pushButtonPnt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButtonPnt.setFont(font)
        self.pushButtonPnt.setObjectName("pushButtonPnt")
        self.gridLayout.addWidget(self.pushButtonPnt, 3, 2, 1, 1)
        self.pushButton5 = QtWidgets.QPushButton(NumPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton5.sizePolicy().hasHeightForWidth())
        self.pushButton5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton5.setFont(font)
        self.pushButton5.setObjectName("pushButton5")
        self.gridLayout.addWidget(self.pushButton5, 1, 1, 1, 1)
        self.pushButton8 = QtWidgets.QPushButton(NumPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton8.sizePolicy().hasHeightForWidth())
        self.pushButton8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton8.setFont(font)
        self.pushButton8.setObjectName("pushButton8")
        self.gridLayout.addWidget(self.pushButton8, 0, 1, 1, 1)
        self.pushButton9 = QtWidgets.QPushButton(NumPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton9.sizePolicy().hasHeightForWidth())
        self.pushButton9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton9.setFont(font)
        self.pushButton9.setObjectName("pushButton9")
        self.gridLayout.addWidget(self.pushButton9, 0, 2, 1, 1)
        self.pushButton4 = QtWidgets.QPushButton(NumPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton4.sizePolicy().hasHeightForWidth())
        self.pushButton4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton4.setFont(font)
        self.pushButton4.setObjectName("pushButton4")
        self.gridLayout.addWidget(self.pushButton4, 1, 0, 1, 1)
        self.pushButton2 = QtWidgets.QPushButton(NumPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton2.sizePolicy().hasHeightForWidth())
        self.pushButton2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton2.setFont(font)
        self.pushButton2.setObjectName("pushButton2")
        self.gridLayout.addWidget(self.pushButton2, 2, 1, 1, 1)
        self.pushButton6 = QtWidgets.QPushButton(NumPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton6.sizePolicy().hasHeightForWidth())
        self.pushButton6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton6.setFont(font)
        self.pushButton6.setObjectName("pushButton6")
        self.gridLayout.addWidget(self.pushButton6, 1, 2, 1, 1)
        self.pushButton3 = QtWidgets.QPushButton(NumPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton3.sizePolicy().hasHeightForWidth())
        self.pushButton3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton3.setFont(font)
        self.pushButton3.setObjectName("pushButton3")
        self.gridLayout.addWidget(self.pushButton3, 2, 2, 1, 1)
        self.pushButton7 = QtWidgets.QPushButton(NumPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton7.sizePolicy().hasHeightForWidth())
        self.pushButton7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton7.setFont(font)
        self.pushButton7.setObjectName("pushButton7")
        self.gridLayout.addWidget(self.pushButton7, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 3, 1)
        self.Yes_pushButton = QtWidgets.QPushButton(NumPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Yes_pushButton.sizePolicy().hasHeightForWidth())
        self.Yes_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Yes_pushButton.setFont(font)
        self.Yes_pushButton.setObjectName("Yes_pushButton")
        self.gridLayout_2.addWidget(self.Yes_pushButton, 2, 1, 1, 1)
        self.No_pushButton = QtWidgets.QPushButton(NumPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.No_pushButton.sizePolicy().hasHeightForWidth())
        self.No_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.No_pushButton.setFont(font)
        self.No_pushButton.setObjectName("No_pushButton")
        self.gridLayout_2.addWidget(self.No_pushButton, 3, 1, 1, 1)
        self.Del_pushButton = QtWidgets.QPushButton(NumPad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Del_pushButton.sizePolicy().hasHeightForWidth())
        self.Del_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Del_pushButton.setFont(font)
        self.Del_pushButton.setObjectName("Del_pushButton")
        self.gridLayout_2.addWidget(self.Del_pushButton, 4, 1, 1, 1)

        self.retranslateUi(NumPad)
        QtCore.QMetaObject.connectSlotsByName(NumPad)

    def retranslateUi(self, NumPad):
        _translate = QtCore.QCoreApplication.translate
        NumPad.setWindowTitle(_translate("NumPad", "NumPad"))
        self.Range_label.setText(_translate("NumPad", " -999999999 ... 999999999"))
        self.newVal_label.setText(_translate("NumPad", "-1234567890"))
        self.pushButton1.setText(_translate("NumPad", "1"))
        self.pushButton0.setText(_translate("NumPad", "0"))
        self.pushButtonSign.setText(_translate("NumPad", "+/-"))
        self.pushButtonPnt.setText(_translate("NumPad", "."))
        self.pushButton5.setText(_translate("NumPad", "5"))
        self.pushButton8.setText(_translate("NumPad", "8"))
        self.pushButton9.setText(_translate("NumPad", "9"))
        self.pushButton4.setText(_translate("NumPad", "4"))
        self.pushButton2.setText(_translate("NumPad", "2"))
        self.pushButton6.setText(_translate("NumPad", "6"))
        self.pushButton3.setText(_translate("NumPad", "3"))
        self.pushButton7.setText(_translate("NumPad", "7"))
        self.Yes_pushButton.setText(_translate("NumPad", "YES"))
        self.No_pushButton.setText(_translate("NumPad", "NO"))
        self.Del_pushButton.setText(_translate("NumPad", "DEL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NumPad = QtWidgets.QDialog()
    ui = Ui_NumPad()
    ui.setupUi(NumPad)
    NumPad.show()
    sys.exit(app.exec_())

